# Generated by Django 5.0.7 on 2024-08-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_comment_user_reply_user_alter_comment_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-publish']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-publish'], 'verbose_name_plural': 'replies'},
        ),
    ]
