# Generated by Django 5.0.7 on 2024-07-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_publish_time',
            new_name='book_publish_year',
        ),
        migrations.AddField(
            model_name='book',
            name='price_validity',
            field=models.CharField(choices=[('n', 'Non-free'), ('f', 'Free')], default='n', help_text="The product can only be priced if the 'Non-free' option is selected", max_length=1),
        ),
    ]
