# Generated by Django 5.0.7 on 2024-08-03 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
