# Generated by Django 5.0.7 on 2024-08-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-publish']},
        ),
    ]
