# Generated by Django 5.0.7 on 2024-08-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_author_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='get_full_name',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='photos',
        ),
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=models.ImageField(default='default/author_default.jpg', upload_to='author_photos/'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='default/category_default.jpg', upload_to='category_photos/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='default/book_default.png', upload_to='book_photos/'),
        ),
    ]
