# Generated by Django 5.0.7 on 2024-08-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_rename_name_author_get_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='get_full_name',
            field=models.CharField(max_length=100, verbose_name='full name'),
        ),
    ]
