# Generated by Django 5.0.7 on 2024-08-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_alter_author_get_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='get_full_name',
            new_name='name',
        ),
    ]
