# Generated by Django 5.0.7 on 2024-08-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_rename_get_full_name_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sell',
            field=models.IntegerField(default=0),
        ),
    ]
