# Generated by Django 5.0.7 on 2024-08-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_book_sell'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-sell']},
        ),
    ]
