# Generated by Django 5.0.7 on 2024-08-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_profile_image'),
        ('book', '0014_rename_get_full_name_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(related_name='orders', to='book.book'),
        ),
    ]
