# Generated by Django 5.0.7 on 2024-08-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_orders'),
        ('book', '0014_rename_get_full_name_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(related_name='cart', to='book.book'),
        ),
    ]
